# Obtener todos los ratings
GET http://localhost:8000/api/ratings/

###
# Obtener todos los ratings
GET http://localhost:8000/api/ratings?desde=0&hasta=5

###
# Obtener un rating específico
GET http://localhost:8000/api/ratings/6745a97914e4f7b1a68ba920

# Modificar un rating
###
PUT http://localhost:8000/api/ratings/6745a97914e4f7b1a68ba918
content-type: application/json

{
  "newRate": 3.5
}
